### ISSUE TITLE
Is there a way to make the Twitter Bootstrap requirement less opinionated?

### ISSUE THREAD

**Issue by abevoelker** [QueueClassic/queue_classic_admin#30]
I'm not super familiar with Rails engines, but I'm already using the `bootstrap-sass` gem in my main Rails application, which is the [official Twitter Bootstrap Sass gem](https://github.com/twbs/bootstrap-sass#a-ruby-on-rails).  It makes me slightly nervous to have multiple bootstrap gems in the same project, although I suppose if this one's well-behaved, it won't matter if I just avoid requiring it in the main application asset pipeline manifest files.

But it would be cool if `queue_classic_admin` could either let me leverage my existing Bootstrap usage, or maybe vendor the Bootstrap source files directly and thus not leak into my application's gems/Gemfile.lock.

I'm probably just being overly paranoid, in which case you can just close this issue.  But I guess I've encountered gems like [`rails_admin`](https://github.com/sferik/rails_admin/blob/78d71104675436150dd74312a6b273078a25d805/rails_admin.gemspec#L8-L20) which went a bit crazy with the view-related gems, and which locked me into dependency hell.  Just food for thought I guess.

**Comment by smathieu** [comment]
You're correct that this is less than ideal. Is it possible to vendor assets like I did in this rails engine https://github.com/smathieu/prosperity 

We should also do the same thing here.

**Comment by abevoelker** [comment]
Yeah that would be simplest in my mind.  Then you wouldn't have to worry about leaking into the user's application gem dependencies.  It was hell for me with `rails_admin` when Bootstrap 3 initially came out, and I imagine it will be hell again whenever 4 comes out.

**Comment by jipiboily** [comment]
This was fixed and I just shipped 1.0.0.beta1 with this and support for queue_classic 3.1 with built-in scheduling.

**Comment by abevoelker** [comment]
Cool, thanks!

**Comment by jipiboily** [comment]
@abevoelker actually, I think there is an issue in the way I added the assets paths...it might not work for you. Hold tighth

**Comment by abevoelker** [comment]
No rush, I won't be able to get back to the project that uses this for some time

**Comment by jipiboily** [comment]
@abevoelker should be good now in theory, pushed a new beta version :)

**Comment by abevoelker** [comment]
:metal:
