### ISSUE TITLE
Latest version of Bootstrap supported?

### ISSUE THREAD

**Issue by Corstiaan84** [QueueClassic/queue_classic_admin#41]
Hi there,

Is the latest version of the Bootstrap (3) gem properly supported? I get an interface that obviously uses bootstrap but the menu and a few buttons are out of wack.

Ideas? :-)

**Comment by smathieu** [comment]
QC Admin uses a vendored version of bootstrap. Can you provide a screenshot of the issue?

**Comment by Corstiaan84** [comment]
I indeed should add some info :-). Please see the attached screenshot.

I did change
```ruby
*= require qc-admin-bootstrap/bootstrap.min
```
into this
I did change
```ruby
*= require bootstrap.min
```
otherwise I got this error:

Sprockets::FileNotFound in QueueClassicAdmin::QueueClassicJobs#index
couldn't find file 'qc-admin-bootstrap/bootstrap.min' with type 'text/css'

![schermafbeelding 2015-11-09 om 10 56 10](https://cloud.githubusercontent.com/assets/3714933/11030802/ac66685a-86d0-11e5-84ec-011e33877bfc.png)

**Comment by smathieu** [comment]
The latest version of the gem should add qc-admin-bootstrap to the asset path. Which version are you using?

```require bootstrap.min``` probably requires another vendored version of bootstrap

**Comment by Corstiaan84** [comment]
Im on 0.2.5



Op 10 november 2015 bij 05:53:37, Simon Mathieu (notifications@github.com) schreef:

**Comment by jipiboily** [comment]
I think I added that after 0.2.5 https://github.com/QueueClassic/queue_classic_admin/commit/38df92948ff2f0a6259aa3ad72e57e67cb0cf6f1 Unless I'm missing something here?

@Corstiaan84 Can you give that beta a shot and report back please?

@ukd1 can you tell me which version of the gem you're using in prod right now? I don't remember if I updated the gem to the beta version back in the days, if yet, we should just release a stable build.

**Comment by jipiboily** [comment]
btw, here's the diff between the latest beta and 0.2.5 (almost nothing): https://github.com/QueueClassic/queue_classic_admin/compare/v0.2.5...v1.0.0.beta2

**Comment by smathieu** [comment]
Updating to `1.0.0.beta2` should fix this. It's pretty stable despite the 'beta' :)

**Comment by Corstiaan84** [comment]
Will test this tomorrow afternoon :-).



Op 10 november 2015 bij 22:46:27, Simon Mathieu (notifications@github.com) schreef:

Updating to 1.0.0.beta2 should fix this. It's pretty stable despite the 'beta' :)

**Comment by jipiboily** [comment]
Closing, I guess it worked as we didn't hear anything frmo @Corstiaan84.

**Comment by Corstiaan84** [comment]
Sorry, i should have replied.

Op maandag 7 december 2015 heeft Jean-Philippe Boily <
notifications@github.com> het volgende geschreven:
